<?php
require_once 'config.php';
require_once __DIR__ . '/vendor/autoload.php'; // TCPDF

session_start();
if (!isset($_SESSION['user'])) {
    header("Location: login.php");
    exit;
}

$user = $_SESSION['user'];
$name = $user['name'];

$start_date = $_GET['start_date'] ?? '';
$end_date = $_GET['end_date'] ?? '';

// Build WHERE clause tanpa DATE() agar index bisa dipakai
$where = "";
if (!empty($start_date) && !empty($end_date)) {
    $where = "WHERE event_time >= '$start_date 00:00:00' AND event_time <= '$end_date 23:59:59'";
} elseif (!empty($start_date)) {
    $where = "WHERE event_time >= '$start_date 00:00:00'";
} elseif (!empty($end_date)) {
    $where = "WHERE event_time <= '$end_date 23:59:59'";
}

// Ambil data
$sql = "SELECT id, slot_number, status, event_time 
        FROM parking_history 
        $where 
        ORDER BY event_time DESC";
$result = mysqli_query($conn, $sql);

// === PDF Setup ===
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('SmartPark System');
$pdf->SetAuthor('SmartPark');
$pdf->SetTitle('Parking History Report');
$pdf->SetMargins(15, 20, 15);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(10);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();

// Header report
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 7, 'Parking History Report', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(0, 6, 'Generated by: '.$name.' | Period: '.(!empty($start_date)?date('d M Y',strtotime($start_date)):'-').' to '.(!empty($end_date)?date('d M Y',strtotime($end_date)):'-'), 0, 1, 'C');
$pdf->Ln(5);

// Column widths
$w = [15, 25, 30, 120]; // No, Slot, Status, DateTime

// Table header
$pdf->SetFont('helvetica', 'B', 10);
$pdf->SetFillColor(252,157,34);
$pdf->SetTextColor(255,255,255);
$pdf->Cell($w[0], 7, 'No', 1, 0, 'C', 1);
$pdf->Cell($w[1], 7, 'Slot Number', 1, 0, 'C', 1);
$pdf->Cell($w[2], 7, 'Status', 1, 0, 'C', 1);
$pdf->Cell($w[3], 7, 'Date & Time', 1, 1, 'C', 1);

// Table rows
$pdf->SetFont('helvetica', '', 10);
$pdf->SetTextColor(0,0,0);
$fill = false;
$no = 1;

while ($row = mysqli_fetch_assoc($result)) {
    // stripe row
    if($fill) {
        $pdf->SetFillColor(249,249,249);
    } else {
        $pdf->SetFillColor(255,255,255);
    }

    $statusText = ($row['status']=='Occupied') ? 'Entered' : 'Exited';

    $pdf->Cell($w[0], 6, $no++, 1, 0, 'C', 1);
    $pdf->Cell($w[1], 6, 'P-'.str_pad($row['slot_number'],2,'0',STR_PAD_LEFT), 1, 0, 'C', 1);
    $pdf->Cell($w[2], 6, $statusText, 1, 0, 'C', 1);
    $pdf->Cell($w[3], 6, date('d M Y, H:i', strtotime($row['event_time'])), 1, 1, 'C', 1);

    $fill = !$fill;

    // Jika halaman penuh, otomatis tambah page & tulis header tabel lagi
    if($pdf->GetY() > 270) { // sekitar margin bawah
        $pdf->AddPage();
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->SetFillColor(252,157,34);
        $pdf->SetTextColor(255,255,255);
        $pdf->Cell($w[0], 7, 'No', 1, 0, 'C', 1);
        $pdf->Cell($w[1], 7, 'Slot Number', 1, 0, 'C', 1);
        $pdf->Cell($w[2], 7, 'Status', 1, 0, 'C', 1);
        $pdf->Cell($w[3], 7, 'Date & Time', 1, 1, 'C', 1);
        $pdf->SetFont('helvetica', '', 10);
        $pdf->SetTextColor(0,0,0);
    }
}

// Output PDF
$pdf->Output('Parking_History_Report.pdf', 'I');
